services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER} -d ${PGDATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: node_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
    env_file:
      - .env
    volumes:
      - app_uploads:/app/public/uploads

volumes:
  pg_data:       # PostgreSQL data persistence
  app_uploads:   # Uploaded images persistence
